CREATE TABLE user_info (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL,
    email VARCHAR2(50),
    phone VARCHAR2(20),
    address VARCHAR2(200),
    PRIMARY KEY(id)
);