-- SYS AS SYSDBA ORCLPDB
CREATE USER admin IDENTIFIED BY admin;
GRANT ALL PRIVILEGES TO admin;

GRANT SELECT ON DBA_USERS TO ADMIN;
GRANT SELECT ON dba_ts_quotas TO ADMIN;
GRANT SELECT ON dba_ROLE_PRIVS TO ADMIN;
